name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release to NPM
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Setup Node.js for NPM
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Type check
      run: bun run typecheck

    - name: Lint
      run: bun run lint

    - name: Build
      run: bun run build

    - name: Test CLI
      run: node dist/cli/test-runner.js --help

    - name: Publish to NPM
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        body: |
          🧪 **@go-corp/test-framework** release ${{ github.ref }}
          
          ## What's New
          
          This release includes improvements to the hybrid test framework for Cloudflare Workers, Node.js, and Bun environments.
          
          ## Installation
          
          ```bash
          npm install @go-corp/test-framework
          # or
          bun add @go-corp/test-framework
          ```
          
          ## Documentation
          
          See the [README](https://github.com/go-corp/test-framework#readme) for full documentation and usage examples.
          
          ---
          
          *This release was automatically created from tag ${{ github.ref }}*